---

- name: stackstorm stack
  hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
    - include_vars: "{{item}}"
      with_items:
        - ../../../account/vars.yml
        - ../env.yml
      tags: always

  roles:
    - role: st2-stack
      tags: always

- include: stackstorm.yml
