site_name: Pentagon
theme: readthedocs


pages:
  - Home: index.md
  - Getting Started: getting-started.md
  - Kops Walkthrough: kops.md
  - VPC: vpc.md
  - Examples: examples.md
  - Namespaces: namespaces.md
  - Open Questions: open-questions.md
  - Overview: overview.md
  - Terminology: terminology.md
  - Virtualenv: virtualenv.md
  - Monitoring: monitoring.md
  - Glossary: glossary.md
