---
- name:  set up vpn prerequisites
  hosts: localhost
  connection: local
  gather_facts: False

  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - ../../../account/vars.yml
        - env.yml
      tags: always

  roles:
    - vpn-stack

- name: configure vpn instance
  hosts: tag_Layer_vpn_public_ip
  become: yes
  become_user: root

  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - ../../../account/vars.yml
        - ../env.yml

  roles:
    - role: Stouts.openvpn-master
      vpn_role: 'primary'
      org: "{{ org_name }}"
      openvpn_first_run: "{{ hostvars['localhost']['openvpn_first_run'] }}"
