---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pentagon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pentagon
    spec:
      volumes:
       - name: htpasswd
         secret:
           secretName: htpasswd
      containers:
      - name: pentagon
        image: 246816220336.dkr.ecr.us-west-2.amazonaws.com/pentagon:latest
        command: ["/bin/bash","-c","service nginx start"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/htpasswd
          name: htpasswd
