---
- name:  create stack
  hosts: localhost
  connection: local
  gather_facts: False

  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - ../../../account/vars.yml
        - ../env.yml
      tags: always

    - set_fact:
        stack_config: "{{ stacks.tesla }}"

  roles:
    - role: tesla-stack
